FROM microsoft/dotnet
MAINTAINER Chris Small for Packt

RUN mkdir /app
COPY ./bin/Release/netcoreapp2.1 /app
WORKDIR /app

ENTRYPOINT ["dotnet", "/app/Sample.dll"]

# ASP.NET Core: Kestrel should listen on all IPs
ENV ASPNETCORE_URLS="http://0.0.0.0:5000"
