FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
MAINTAINER Chris Small for Packt

RUN mkdir /app
COPY ./bin/Release/netcoreapp3.1 /app
WORKDIR /app

ENTRYPOINT ["dotnet", "/app/ApiManager.dll"]

# ASP.NET Core: Kestrel should listen on all IPs
ENV ASPNETCORE_URLS="http://0.0.0.0:5000"
